services:
  postgres:
    image: postgres:17
    ports:
      - "25432:5432"
    volumes:
      - "./data:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  temporal:
    image: temporalio/auto-setup:latest
    ports:
      - "7233:7233"
    depends_on:
      - postgres
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - DB=postgres12
      - DB_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PWD=postgres
      - POSTGRES_SEEDS=postgres
      - POSTGRES_DB=temporal
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development.yaml
    volumes:
      - ./dynamicconfig:/etc/temporal/config/dynamicconfig

  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
      - POSTGRES_USER=postgres
      - POSTGRES_PASS=postgres
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DB=postgresql
      - DB_PORT=5432
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASS=postgres
