services:
  postgres:
    image: postgres:17
    ports:
      - "25432:5432"
    volumes:
      - "pg-data:/var/lib/postgresql/data"
      - "./init.sql:/docker-entrypoint-initdb.d/init.sql"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  temporal:
    image: temporalio/auto-setup:latest
    ports:
      - "7233:7233"
    depends_on:
      - postgres
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - DB=agentic_temporal_dev
      - DB_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PWD=postgres
      - POSTGRES_SEEDS=postgres
      - POSTGRES_DB=temporal
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development.yaml
    volumes:
      - ./dynamicconfig:/etc/temporal/config/dynamicconfig

  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DB=agentic_dev
      - DB_PORT=5432
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASS=postgres

volumes:
  pg-data:
